#!/usr/bin/env python3
"""
download_pdfs.py — Download all PDFs from the inventory CSV.

Features:
  - Resume-safe: skips already-downloaded files (checks disk before fetching)
  - Rate-limited: 0.5s delay between requests to be polite to the server
  - Error logging: all failures (HTTP errors, timeouts, non-PDF responses)
    are written to data/download_errors.csv for later review
  - PDF header validation: confirms each response starts with %PDF

Usage:
    python download/download_pdfs.py

Expected input: data/pdf_inventory.csv (generated by inventory/build_url_inventory.py)
Output directory: data/pdfs/ (gitignored)
Error log: data/download_errors.csv
"""

import csv
import os
import time
from pathlib import Path

import requests

requests.packages.urllib3.disable_warnings()

INVENTORY = Path("data/pdf_inventory.csv")
PDF_DIR = Path("data/pdfs")
ERRORS = Path("data/download_errors.csv")
DELAY = 0.5  # seconds between requests
HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; FrenchParliamentaryCorpus/1.0)"}

PDF_DIR.mkdir(parents=True, exist_ok=True)


def _make_filename(row: dict) -> str:
    """Build a collision-safe filename: {legislature}_{session}_{url_basename}.

    Including the session prevents collisions when different sessions use the
    same sequential numbering (e.g. Legislature 11).
    """
    leg = row["legislature"]
    session = row["session"]
    basename = Path(row["url"]).name
    # Sanitise: replace any path separators that snuck through
    session_clean = session.replace("/", "-").replace("\\", "-")
    return f"{leg}_{session_clean}_{basename}"


def _cleanup_old_style_files(inventory_rows: list[dict]) -> int:
    """Remove old collision-prone Leg 11 files.

    Legislature 11 uses sequential numbering (001.pdf, 002.pdf, ...) in
    every session, so the old naming scheme {leg}_{basename}.pdf caused
    ~902 collisions across 8 sessions.  We remove the old files so the
    new scheme {leg}_{session}_{basename}.pdf can replace them.

    Legs 12-17 are left alone — their date-based or descriptive basenames
    never collided, and their old-style files are retained (the download
    loop's fallback check skips them).

    Returns the number of files removed.
    """
    removed = 0
    for row in inventory_rows:
        if row['legislature'] != '11':
            continue
        old_path = PDF_DIR / f"{row['legislature']}_{Path(row['url']).name}"
        if old_path.exists():
            old_path.unlink()
            removed += 1
    return removed


def download_all(cleanup_old: bool = True) -> None:
    """Download all PDFs not already on disk, logging errors."""
    if not INVENTORY.exists():
        print(f"Inventory not found at {INVENTORY}. Run inventory/build_url_inventory.py first.")
        return

    with open(INVENTORY, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    print(f"Total PDFs in inventory: {len(rows)}")

    if cleanup_old:
        old_count = _cleanup_old_style_files(rows)
        if old_count > 0:
            print(f"Cleaned up {old_count} old-style collision files (Leg 11).")

    # Count already-downloaded: check new name first, fall back to old name
    done = 0
    for r in rows:
        new_path = PDF_DIR / _make_filename(r)
        old_path = PDF_DIR / f"{r['legislature']}_{Path(r['url']).name}"
        if new_path.exists() or old_path.exists():
            done += 1
    print(f"Already downloaded: {done}")
    print(f"Remaining: {len(rows) - done}\n")

    errors: list[dict] = []
    downloaded = 0

    for i, row in enumerate(rows):
        new_path = PDF_DIR / _make_filename(row)
        old_path = PDF_DIR / f"{row['legislature']}_{Path(row['url']).name}"

        # Skip if already downloaded under either naming scheme
        if new_path.exists() or old_path.exists():
            continue

        url = row["url"]
        try:
            r = requests.get(url, headers=HEADERS, verify=False, timeout=30)

            if r.status_code == 200 and r.content[:4] == b"%PDF":
                new_path.write_bytes(r.content)
                downloaded += 1
                if downloaded % 50 == 0:
                    print(f"  [{i+1}/{len(rows)}] Downloaded {downloaded} new PDFs...")
            else:
                errors.append({**row, "status": r.status_code, "reason": "not a PDF"})
                print(f"  SKIP {r.status_code} {url}")

            time.sleep(DELAY)

        except Exception as e:
            errors.append({**row, "status": "ERR", "reason": str(e)})
            print(f"  ERR {url}: {e}")

    # Write error log
    with open(ERRORS, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["legislature", "session", "url", "status", "reason"])
        writer.writeheader()
        writer.writerows(errors)

    print(f"\n✅ Done. {downloaded} new PDFs downloaded.")
    print(f"   Errors: {len(errors)} — see {ERRORS}")
    print(f"   Total on disk: {len(list(PDF_DIR.glob('*.pdf')))}")


if __name__ == "__main__":
    download_all()
