#!/usr/bin/env python3
"""
download_pdfs.py — Download all PDFs from the inventory CSV.

Features:
  - Resume-safe: skips already-downloaded files (checks disk before fetching)
  - Rate-limited: 0.5s delay between requests to be polite to the server
  - Error logging: all failures (HTTP errors, timeouts, non-PDF responses)
    are written to data/download_errors.csv for later review
  - PDF header validation: confirms each response starts with %PDF

Usage:
    python download/download_pdfs.py

Expected input: data/pdf_inventory.csv (generated by inventory/build_url_inventory.py)
Output directory: data/pdfs/ (gitignored)
Error log: data/download_errors.csv
"""

import csv
import os
import time
from pathlib import Path

import requests

requests.packages.urllib3.disable_warnings()

INVENTORY = Path("data/pdf_inventory.csv")
PDF_DIR = Path("data/pdfs")
ERRORS = Path("data/download_errors.csv")
DELAY = 0.5  # seconds between requests
HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; FrenchParliamentaryCorpus/1.0)"}

PDF_DIR.mkdir(parents=True, exist_ok=True)


def download_all() -> None:
    """Download all PDFs not already on disk, logging errors."""
    if not INVENTORY.exists():
        print(f"❌ Inventory not found at {INVENTORY}. Run inventory/build_url_inventory.py first.")
        return

    with open(INVENTORY, encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    print(f"Total PDFs in inventory: {len(rows)}")

    # Count already-downloaded
    done = sum(
        1 for r in rows
        if Path(PDF_DIR, f"{r['legislature']}_{Path(r['url']).name}").exists()
    )
    print(f"Already downloaded: {done}")
    print(f"Remaining: {len(rows) - done}\n")

    errors: list[dict] = []
    downloaded = 0

    for i, row in enumerate(rows):
        leg = row["legislature"]
        url = row["url"]
        filename = f"{leg}_{Path(url).name}"
        filepath = PDF_DIR / filename

        if filepath.exists():
            continue

        try:
            r = requests.get(url, headers=HEADERS, verify=False, timeout=30)

            if r.status_code == 200 and r.content[:4] == b"%PDF":
                filepath.write_bytes(r.content)
                downloaded += 1
                if downloaded % 50 == 0:
                    print(f"  [{i+1}/{len(rows)}] Downloaded {downloaded} new PDFs...")
            else:
                errors.append({**row, "status": r.status_code, "reason": "not a PDF"})
                print(f"  SKIP {r.status_code} {url}")

            time.sleep(DELAY)

        except Exception as e:
            errors.append({**row, "status": "ERR", "reason": str(e)})
            print(f"  ERR {url}: {e}")

    # Write error log
    with open(ERRORS, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["legislature", "session", "url", "status", "reason"])
        writer.writeheader()
        writer.writerows(errors)

    print(f"\n✅ Done. {downloaded} new PDFs downloaded.")
    print(f"   Errors: {len(errors)} — see {ERRORS}")
    print(f"   Total on disk: {len(list(PDF_DIR.glob('*.pdf')))}")


if __name__ == "__main__":
    download_all()
